spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
  mvc:
    hiddenmethod.filter.enabled: true
  application:
    days_until_book_overdue: 10

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %clr(%5level) [%15.15t] %clr(%-45.55logger{39}){cyan} : %m%n%wEx"
  level:
    org:
      springframework:
        web: INFO
      thymeleaf: OFF
      hibernate:
        SQL: OFF
        orm:
          results: INFO
        validator: WARN
    ru.saneci.booklibrary: INFO